# Generated by Django 4.1.7 on 2023-03-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_product_options_alter_review_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="webapp.product",
                verbose_name="Товар",
            ),
        ),
    ]
